"""document artifacts

Revision ID: 20260816_0002
Revises: 20260816_0001
Create Date: 2026-08-16 22:44:52.016846
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260816_0002'
down_revision: Union[str, Sequence[str], None] = '20260816_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('markdown_path', sa.Text(), nullable=False),
    sa.Column('document_json_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attachment_id', 'source_sha256', 'parser_name', 'parser_version', name='uq_document_artifact_parser')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_artifacts')
    # ### end Alembic commands ###
